"""Initial migration

Revision ID: 650a21474271
Revises: 
Create Date: 2026-09-01 01:02:35.501291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650a21474271'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('actor_email', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_resource', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('call_reason', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('resolved', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_customer_id'), 'call_logs', ['customer_id'], unique=False)
    op.create_table('customer_scores',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('plan_tier', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('monthly_charges', sa.Float(), nullable=True),
    sa.Column('total_charges', sa.Float(), nullable=True),
    sa.Column('churn_probability', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('clv', sa.Float(), nullable=True),
    sa.Column('usage_drop_call_pct', sa.Float(), nullable=True),
    sa.Column('usage_drop_data_pct', sa.Float(), nullable=True),
    sa.Column('support_calls_m1', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('pca_x', sa.Float(), nullable=True),
    sa.Column('pca_y', sa.Float(), nullable=True),
    sa.Column('shap_json', sa.Text(), nullable=True),
    sa.Column('recommendation_json', sa.Text(), nullable=True),
    sa.Column('actioned', sa.Integer(), nullable=True),
    sa.Column('actioned_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('plan_tier', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('monthly_charges', sa.Float(), nullable=True),
    sa.Column('total_charges', sa.Float(), nullable=True),
    sa.Column('call_minutes_m1', sa.Float(), nullable=True),
    sa.Column('call_minutes_m2', sa.Float(), nullable=True),
    sa.Column('call_minutes_m3', sa.Float(), nullable=True),
    sa.Column('data_gb_m1', sa.Float(), nullable=True),
    sa.Column('data_gb_m2', sa.Float(), nullable=True),
    sa.Column('data_gb_m3', sa.Float(), nullable=True),
    sa.Column('recharge_count_m1', sa.Integer(), nullable=True),
    sa.Column('recharge_count_m2', sa.Integer(), nullable=True),
    sa.Column('recharge_count_m3', sa.Integer(), nullable=True),
    sa.Column('support_calls_m1', sa.Integer(), nullable=True),
    sa.Column('support_calls_m2', sa.Integer(), nullable=True),
    sa.Column('support_calls_m3', sa.Integer(), nullable=True),
    sa.Column('churn', sa.Integer(), nullable=True),
    sa.Column('usage_drop_call_pct', sa.Float(), nullable=True),
    sa.Column('usage_drop_data_pct', sa.Float(), nullable=True),
    sa.Column('support_call_trend', sa.Integer(), nullable=True),
    sa.Column('avg_monthly_recharges', sa.Float(), nullable=True),
    sa.Column('tenure_bucket', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('monitoring_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monitoring_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('features_checked', sa.Integer(), nullable=False),
    sa.Column('features_drifted', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitoring_id')
    )
    op.create_table('performance_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('performance_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=False),
    sa.Column('roc_auc', sa.Float(), nullable=False),
    sa.Column('pr_auc', sa.Float(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('performance_id')
    )
    op.create_table('prediction_history',
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('churn_probability', sa.Float(), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('prediction_timestamp', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_prediction_history_customer_id'), 'prediction_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_prediction_history_prediction_timestamp'), 'prediction_history', ['prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_prediction_history_risk_tier'), 'prediction_history', ['risk_tier'], unique=False)
    op.create_table('segment_profiles',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('avg_tenure_months', sa.Float(), nullable=True),
    sa.Column('avg_monthly_charges', sa.Float(), nullable=True),
    sa.Column('avg_total_charges', sa.Float(), nullable=True),
    sa.Column('avg_usage_drop_call_pct', sa.Float(), nullable=True),
    sa.Column('avg_usage_drop_data_pct', sa.Float(), nullable=True),
    sa.Column('avg_support_calls_m1', sa.Float(), nullable=True),
    sa.Column('avg_churn_probability', sa.Float(), nullable=True),
    sa.Column('actual_churn_rate', sa.Float(), nullable=True),
    sa.Column('avg_clv', sa.Float(), nullable=True),
    sa.Column('avg_priority_score', sa.Float(), nullable=True),
    sa.Column('high_risk_count', sa.Integer(), nullable=True),
    sa.Column('critical_risk_count', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('risk_category', sa.String(), nullable=True),
    sa.Column('recommended_strategy', sa.String(), nullable=True),
    sa.Column('eligible_customers', sa.Integer(), nullable=True),
    sa.Column('estimated_campaign_cost', sa.Float(), nullable=True),
    sa.Column('estimated_retention_opportunity', sa.Float(), nullable=True),
    sa.Column('estimated_roi_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_profiles')
    op.drop_index(op.f('ix_prediction_history_risk_tier'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_prediction_timestamp'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_customer_id'), table_name='prediction_history')
    op.drop_table('prediction_history')
    op.drop_table('performance_history')
    op.drop_table('monitoring_history')
    op.drop_table('customers')
    op.drop_table('customer_scores')
    op.drop_index(op.f('ix_call_logs_customer_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
