"""Add created_at to customer_scores table

Revision ID: 7e5ee14aefa5
Revises: 650a21474271
Create Date: 2026-09-01 21:55:05.669000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5ee14aefa5'
down_revision: Union[str, Sequence[str], None] = '650a21474271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_scores', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_scores', 'created_at')
    # ### end Alembic commands ###
